server:
  port: 8081

spring:
  application:
    name: user
  datasource:
    url: ENC(Wak/a5yg1CCPFb9xJUK39RLueFwXQjOptfZ3Aw4dhZRqcYUBatGYWirVS4IpqeZwvd32kZQ9r2YYsrMa0Tg7+A==)
    username: ENC(E3X+YVg3OGUlanxyEr1oxsTxhfIytU2S)
    password: ENC(PrfDuc2GADVS7iDBiQP171uUYe1fyfFC)
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

jasypt:
  encryptor:
    property:
      bean: jasyptStringEncryptor
    password: ${SECRET_KEY}

aes:
  password: ENC(yGEk/YjqUhn34BwblUO5mQapkJ/2A+J3ux4JRuYFTiTEkXjy7D5hp5tZNATimMjOopJlQZaMmVk=)
  salt: ENC(g/sMb9wlbW7WYrHl4AyKfz0lehFy5An7RIQXR2FpFs63onbNvMCrkQ==)

jwt:
  secret: ENC(nv2zQD07ToGj4ULUjnwOrWI+5wjIQo6GE4QZFbDiGSenOxv1G714D0DUZKznorOX85bUP+yTSl8=)

logging:
  level:
    root: debug
    com.zerobase: debug

