server:
  port: 9001

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/users/**, /login/**, /login/oauth2/code/**

        - id: challenge
          uri: lb://challenge
          predicates:
            - Path=/challenges/**
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ENC(PuUyduub8CcHkWuV2S4M+caPFpNHpeYvLe0g6QQ/aejfUKR8O1aurKsEce1JmOAw5vbDyhZrmUrG/DsjyKEyEkqdVjpwh0TfckosdjeWz2xXp+kb3u2W5A==)
            client-secret: ENC(uwbo7wPKRhAfaO27WtX12K9CoYoGx8VDqorHZ0FR6TUSECwm3BSiOjY65VQBkPiY)
            scope: profile, email
            redirect-uri: "http://localhost:9001/login/oauth2/code/google"
          naver:
            client-id: ENC(W+NdnBnyApQx9H5+WdFjqaVBIV8bMFCe+ayebQoFnWA=)
            client-secret: ENC(mg4vLRzJkhEof9h5ddhe1X5RWVxeE6qs)
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: name, email, nickname
            redirect-uri: "http://localhost:9001/login/oauth2/code/naver"
            client-name: naver
          kakao:
            client-id: ENC(PEzANOvS2lchMDjVqQhLbb3HbyDu8pJYrriNSjNRJNWX/Q8cLKmlAHHLJowuM+1p)
            client-secret: ENC(IM4E35MWymwZAEEZPpdLS2t2E+RxAeyiDrI+yuNpo0W5g+0mEbjVZ8zWyHAQ2FmB)
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image
            redirect-uri: "http://localhost:9001/login/oauth2/code/kakao"
            client-name: kakao
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize?auth_type=reauthenticate
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-info-authentication-method: header
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize?prompt=login
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: header
            user-name-attribute: id


  main:
    allow-bean-definition-overriding: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"

jwt:
  secret: ENC(nv2zQD07ToGj4ULUjnwOrWI+5wjIQo6GE4QZFbDiGSenOxv1G714D0DUZKznorOX85bUP+yTSl8=)

jasypt:
  encryptor:
    property:
      bean: jasyptStringEncryptor
    password: ${SECRET_KEY}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: debug
    org.springframework.web: debug
    reactor.netty.http.client: DEBUG
    root: debug
    com.zerobase.apigateway: debug