spring:
  application:
    name: common

jwt:
  secret: ENC(nv2zQD07ToGj4ULUjnwOrWI+5wjIQo6GE4QZFbDiGSenOxv1G714D0DUZKznorOX85bUP+yTSl8=)

jasypt:
  encryptor:
    property:
      bean: jasyptStringEncryptor
    password: ${SECRET_KEY}