### Get CSRF Token
GET http://localhost:8080/csrf-token
Content-Type: application/json

###회원가입
POST http://localhost:8081/users/register
Content-Type: application/json

{
  "username": "testUser2",
  "password": "Test@1234",
  "email": "test2@example.com",
  "phoneNumber": "01012345679",
  "nickName": "TestNick",
  "name": "Test Name",
  "birth": "1990-01-01",
  "job": "학생",
  "interests": "개발",
  "gender": "MALE"
}

### 자체 서비스 로그인
POST http://localhost:8081/users/login
Content-Type: application/json

{
  "username": "testUser2",
  "password": "Test@1234"
}

### 나의 정보 조회
GET http://localhost:8081/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwic3ViIjoidGVzdFVzZXIyIiwiaWF0IjoxNzIwNzk3NTU4LCJleHAiOjE3MjA3OTkzNTh9.fEihtc6SqZHo5x12isdQcig9KN_-ucrHL-ECkahM720
Refresh: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdXRob3JpdGllcyI6W10sInN1YiI6InRlc3RVc2VyMiIsImlhdCI6MTcyMDc5NzU1OCwiZXhwIjoxNzIxNDAyMzU4fQ.uVkh1w0x90h6P_j52DAuLYkB958-xJUa0NS8ED4X2E0
### 정보 수정
PUT http://localhost:8080/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwic3ViIjoidGVzdFVzZXIiLCJpYXQiOjE3MjA1MDkzMjEsImV4cCI6MTcyMDUxMDIyMX0.XOt_gLGBwE4b8eVbKGerJHXKlieJ_T567PDwcm2CxOk

{
  "nickName": "Test-update",
  "name": "Test-update",
  "job": "학생",
  "interests": "백엔드 개발",
  "gender": "MALE"
}

### 회원 탈퇴
DELETE http://localhost:8080/users/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwic3ViIjoidGVzdFVzZXIiLCJpYXQiOjE3MjAzNTQ4OTksImV4cCI6MTcyMDM5MDg5OX0.r4TFfW9PHg1SgLojgb3EtTePEnudBLQyscU2xQW4w2A

### 토큰 재발급
POST http://localhost:8081/users/refresh
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwic3ViIjoidGVzdFVzZXIiLCJpYXQiOjE3MjA3OTcxNDIsImV4cCI6MTcyMDc5ODk0Mn0.-aiQ1Gw4gbpO4WH4zz643UpjrjVjZHGLfOEmpJW2FdM
Refresh: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdXRob3JpdGllcyI6W10sInN1YiI6InRlc3RVc2VyIiwiaWF0IjoxNzIwNzk3MTQyLCJleHAiOjE3MjE0MDE5NDJ9.d-XXsCFpLR1AHRDnaBZCzjJcZyptGLjwBPT7g12fw-w


### 로그아웃
POST http://localhost:8080/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwic3ViIjoidGVzdFVzZXIiLCJpYXQiOjE3MjA1OTE1NjgsImV4cCI6MTcyMDU5MzM2OH0.Y_jxvuMZbk6YUhQtkyiQtgobuqbjiDPn3-X5DPmABcI
Refresh: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdXRob3JpdGllcyI6W10sInN1YiI6InRlc3RVc2VyIiwiaWF0IjoxNzIwNTkxNTY4LCJleHAiOjE3MjExOTYzNjh9.PgnWNKSwKfJyA7rU94EHQTPF6uyvWr23Gr3MGZX1liE

